<?php

/*
 * This file is part of the flarum-translations.
 *
 * Copyright (c) 2019 Robert Korulczyk <robert@korulczyk.pl>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

declare(strict_types=1);

return [
	'af' => [],
	'ar' => [],
	'ast' => [],
	'az' => [],
	'be' => [],
	'bg' => [],
	'bn' => [],
	'br' => [],
	'bs' => [],
	'ca' => [],
	'ckb' => [],
	'cs' => [],
	'cy' => [],
	'da' => [],
	'de' => [],
	'de@formal' => [],
	'el' => [],
	'eo' => [],
	'es' => [],
	'es@formal' => [],
	'es_AR' => [],
	'es_MX' => [],
	'et' => [],
	'eu' => [],
	'fa' => [],
	'fi' => [],
	'fil' => [],
	'fr' => [],
	'ga' => [],
	'gl' => [],
	'he' => [],
	'hi' => [],
	'hr' => [],
	'hu' => [],
	'hy' => [],
	'id' => [],
	'is' => [],
	'it' => [],
	'ja' => [],
	'ka' => [],
	'kab' => [],
	'kk' => [],
	'km' => [],
	'kmr' => [],
	'kn' => [],
	'ko' => [],
	'lt' => [],
	'lv' => [],
	'mk' => [],
	'ml' => [],
	'mr' => [],
	'my' => [],
	'nb' => [],
	'ne' => [],
	'nl' => [],
	'nn' => [],
	'oc' => [],
	'pa' => [],
	'pl' => [],
	'pt' => [],
	'pt_BR' => [],
	'ro' => [],
	'ru' => [],
	'sc' => [],
	'si' => [],
	'sk' => [],
	'sl' => [],
	'sq' => [],
	'sr_Cyrl' => [],
	'sr_Latn' => [],
	'sv' => [],
	'ta' => [],
	'te' => [],
	'tg' => [],
	'th' => [],
	'tk' => [],
	'tl' => [],
	'tok' => [],
	'tr' => [],
	'tt' => [],
	'ug' => [],
	'uk' => [],
	'ur' => [],
	'uz' => [],
	'vi' => [],
	'zh_Hans' => [],
	'zh_Hant' => [],
];
