<?php

/*
 * This file is part of the flarum-translations.
 *
 * Copyright (c) 2019 Robert Korulczyk <robert@korulczyk.pl>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

return [
	'__weblateId' => 'flarum-extensions',
	// do not remove this component - it is used as main component in this project
	'core' => 'https://raw.githubusercontent.com/rob006-software/flarum-translations/master/placeholders/various.yml',
	/* extensions list begin */
	'amaurycarrade-syndication' => 'https://raw.githubusercontent.com/AmauryCarrade/flarum-ext-syndication/master/resources/locale/en.yml',
	'antoinefr-money' => 'https://raw.githubusercontent.com/AntoineFr/flarum-ext-money/master/locale/en.yml',
	'antoinefr-online' => 'https://raw.githubusercontent.com/AntoineFr/flarum-ext-online/master/locale/en.yml',
	'clarkwinkelmann-author-change' => 'https://raw.githubusercontent.com/clarkwinkelmann/flarum-ext-author-change/master/resources/locale/en.yml',
	'clarkwinkelmann-carving-contest' => 'https://raw.githubusercontent.com/clarkwinkelmann/flarum-ext-carving-contest/master/resources/locale/en.yml',
	'clarkwinkelmann-catch-the-fish' => 'https://raw.githubusercontent.com/clarkwinkelmann/catch-the-fish/master/resources/locale/en.yml',
	'clarkwinkelmann-create-user-modal' => 'https://raw.githubusercontent.com/clarkwinkelmann/flarum-ext-create-user-modal/master/resources/locale/en.yml',
	'clarkwinkelmann-email-as-display-name' => 'https://raw.githubusercontent.com/clarkwinkelmann/flarum-ext-email-as-display-name/master/locale/en.yml',
	'clarkwinkelmann-emojionearea' => 'https://raw.githubusercontent.com/clarkwinkelmann/flarum-ext-emojionearea/master/locale/en.yml',
	'clarkwinkelmann-passwordless' => 'https://raw.githubusercontent.com/clarkwinkelmann/flarum-ext-passwordless/master/resources/locale/en.yml',
	'clarkwinkelmann-post-date' => 'https://raw.githubusercontent.com/clarkwinkelmann/flarum-ext-post-date/master/resources/locale/en.yml',
	'clarkwinkelmann-status' => 'https://raw.githubusercontent.com/clarkwinkelmann/flarum-ext-status/master/resources/locale/en.yml',
	'datitisev-dashboard' => 'https://raw.githubusercontent.com/datitisev/flarum-ext-dashboard/master/resources/locale/en.yml',
	'dem13n-auth-mailru' => 'https://raw.githubusercontent.com/Dem13n/auth-mailru/master/resources/locale/en.yml',
	'dem13n-auth-odnoklassniki' => 'https://raw.githubusercontent.com/Dem13n/auth-odnoklassniki/master/resources/locale/en.yml',
	'dem13n-auth-vkontakte' => 'https://raw.githubusercontent.com/Dem13n/auth-vkontakte/master/resources/locale/en.yml',
	'dem13n-auth-yandex' => 'https://raw.githubusercontent.com/Dem13n/auth-yandex/master/resources/locale/en.yml',
	'dem13n-nickname-changer' => 'https://raw.githubusercontent.com/Dem13n/nickname-changer/master/resources/locale/en.yml',
	'dem13n-quad-theme' => 'https://raw.githubusercontent.com/Dem13n/quad-theme/master/resources/locale/en.yml',
	'dexif-telegram' => 'https://raw.githubusercontent.com/dexif/telegram/dexif/resources/locale/en.yml',
	'dotronglong-hide-me' => 'https://raw.githubusercontent.com/dotronglong/flarum-hide-me/master/locale/en.yml',
	'extiverse-bazaar' => 'https://raw.githubusercontent.com/extiverse/bazaar/master/resources/locale/en.yml',
	'fajuu-contactbutton' => 'https://raw.githubusercontent.com/Fajuu/ContactButton/master/locale/en.yml',
	'fajuu-icons' => 'https://raw.githubusercontent.com/Fajuu/flarum-icons/master/resources/locale/en.yml',
	'flagrow-ads' => 'https://raw.githubusercontent.com/FriendsOfFlarum/ads/master/locale/en.yml',
	'flagrow-analytics' => 'https://raw.githubusercontent.com/flagrow/analytics/master/resources/locale/en.yml',
	'flagrow-fonts' => 'https://raw.githubusercontent.com/flagrow/fonts/master/resources/locale/en.yml',
	'flagrow-impersonate' => 'https://raw.githubusercontent.com/flagrow/impersonate/master/resources/locale/en.yml',
	'flagrow-mason' => 'https://raw.githubusercontent.com/flagrow/mason/master/resources/locale/en.yml',
	'flagrow-passport' => 'https://raw.githubusercontent.com/flagrow/passport/master/locale/en.yml',
	'flagrow-upload' => 'https://raw.githubusercontent.com/FriendsOfFlarum/upload/master/resources/locale/en.yml',
	'giga300-auth-discord' => 'https://raw.githubusercontent.com/giga300/flarum-auth-discord/master/locale/en.yml',
	'hiqstd-close' => 'https://raw.githubusercontent.com/HiQStd/flarum-ext-close/master/resources/locale/en.yml',
	'irony-bing-wallpaper' => 'https://raw.githubusercontent.com/892768447/flarum-ext-bing-wallpaper/master/resources/locale/en.yml',
	'irony-code-insert' => 'https://raw.githubusercontent.com/892768447/flarum-ext-code-insert/master/resources/locale/en.yml',
	'irony-google-search' => 'https://raw.githubusercontent.com/892768447/flarum-ext-google-search/master/resources/locale/en.yml',
	'irony-login2see' => 'https://raw.githubusercontent.com/892768447/flarum-ext-login2see/master/resources/locale/en.yml',
	'irony-webhook' => 'https://raw.githubusercontent.com/892768447/flarum-ext-webhook/master/resources/locale/en.yml',
	'kilowhat-affiliation-links' => 'https://raw.githubusercontent.com/kilowhat/flarum-ext-affiliation-links/master/resources/locale/en.yml',
	'kilowhat-mailing' => 'https://raw.githubusercontent.com/kilowhat/flarum-ext-mailing/master/resources/locale/en.yml',
	'kvothe-keyboard-shortcuts' => 'https://raw.githubusercontent.com/oaklinq/flarum-ext-keyboard-shortcuts/master/resources/locale/en.yml',
	'kvothe-reply-to-see' => 'https://raw.githubusercontent.com/oaklinq/flarum-ext-reply2see/master/resources/locale/en.yml',
	'kvothe-signup-button' => 'https://raw.githubusercontent.com/oaklinq/flarum-signup-button/master/resources/locale/en.yml',
	'kvothe-spoiler-bbcode' => 'https://raw.githubusercontent.com/oaklinq/flarum-ext-spoiler-bbcode/master/resources/locale/en.yml',
	'maicol07-sso' => 'https://raw.githubusercontent.com/maicol07/flarum-ext-sso/master/locale/en.yml',
	'manelizzard-notify' => 'https://raw.githubusercontent.com/manelizzard/flarum-notify/master/resources/locale/en.yml',
	'matteocontrini-imgur-upload' => 'https://raw.githubusercontent.com/matteocontrini/flarum-imgur-upload/master/locale/en.yml',
	'michaelbelgium-discussion-views' => 'https://raw.githubusercontent.com/MichaelBelgium/flarum-discussion-views/master/locale/en.yml',
	'michaelbelgium-mybb-to-flarum' => 'https://raw.githubusercontent.com/MichaelBelgium/mybb_to_flarum/master/locale/en.yml',
	'michaelbelgium-profile-views' => 'https://raw.githubusercontent.com/MichaelBelgium/flarum-profile-views/master/locale/en.yml',
	'migratetoflarum-canonical' => 'https://raw.githubusercontent.com/migratetoflarum/canonical/master/resources/locale/en.yml',
	'migratetoflarum-fake-data' => 'https://raw.githubusercontent.com/migratetoflarum/fake-data/master/resources/locale/en.yml',
	'migratetoflarum-itemlist-order' => 'https://raw.githubusercontent.com/migratetoflarum/itemlist-order/master/resources/locale/en.yml',
	'migratetoflarum-vbulletin-redirects' => 'https://raw.githubusercontent.com/migratetoflarum/vbulletin-redirects/master/locale/en.yml',
	'minr-auth-qq' => 'https://raw.githubusercontent.com/minr/flarum-ext-auth-qq/master/locale/en.yml',
	'minr-auth-weibo' => 'https://raw.githubusercontent.com/minr/auth-weibo/master/locale/en.yml',
	'nikovonlas-auth-vk' => 'https://raw.githubusercontent.com/NikoVonLas/flarum-ext-auth-vk/master/locale/en.yml',
	'nikovonlas-web-push' => 'https://raw.githubusercontent.com/NikoVonLas/flarum-ext-web-push/master/locale/en.yml',
	'nomiscz-auth-linkedin' => 'https://raw.githubusercontent.com/NomisCZ/flarum-ext-auth-linkedin/master/resources/locale/en.yml',
	'nomiscz-auth-steam' => 'https://raw.githubusercontent.com/NomisCZ/flarum-ext-auth-steam/master/resources/locale/en.yml',
	'reflar-cookie-consent' => 'https://raw.githubusercontent.com/ReFlar/cookie-consent/master/resources/locale/en.yml',
	'reflar-doorman' => 'https://raw.githubusercontent.com/ReFlar/doorman/master/resources/locale/en.yml',
	'reflar-level-ranks' => 'https://raw.githubusercontent.com/ReFlar/level-ranks/master/resources/locale/en.yml',
	'reflar-twofactor' => 'https://raw.githubusercontent.com/ReFlar/twofactor/master/resources/locale/en.yml',
	'reflar-webhooks' => 'https://raw.githubusercontent.com/ReFlar/webhooks/master/resources/locale/en.yml',
	'saleksin-auth-google' => 'https://raw.githubusercontent.com/saleksin/flarum-auth-google/master/locale/en.yml',
	'shriker-pronouns' => 'https://raw.githubusercontent.com/shriker/flarum-pronouns/master/resources/locale/en.yml',
	'squeevee-fancybox' => 'https://raw.githubusercontent.com/squeevee/flarum-ext-fancybox/master/locale/en.yml',
	'sycho-profile-cover' => 'https://raw.githubusercontent.com/SychO9/flarum-profile-cover/master/resources/locale/en.yml',
	'tank-perspective' => 'https://raw.githubusercontent.com/tankerkiller125/flarum-perspective/master/resources/locale/en.yml',
	'the-turk-mathren' => 'https://raw.githubusercontent.com/the-turk/flarum-mathren/master/locale/en.yml',
	'the-turk-password-strength' => 'https://raw.githubusercontent.com/the-turk/flarum-password-strength/master/locale/en.yml',
	'tituspijean-auth-ldap' => 'https://raw.githubusercontent.com/tituspijean/flarum-ext-auth-ldap/master/locale/en.yml',
	'tituspijean-auth-ssowat' => 'https://raw.githubusercontent.com/tituspijean/flarum-ext-auth-ssowat/master/locale/en.yml',
	'tpokorra-post-notification' => 'https://raw.githubusercontent.com/tpokorra/flarum-ext-post-notification/master/resources/locale/en.yml',
	'v17development-seo' => 'https://raw.githubusercontent.com/v17development/flarum-seo/master/locale/en.yml',
	'veriael-markdown' => 'https://raw.githubusercontent.com/Veriael/markdown/master/resources/locale/en.yml',
	'wiwatsrt-best-answer' => 'https://raw.githubusercontent.com/wiwatsrt/flarum-ext-best-answer/master/locale/en.yml',
	'xmugenx-post-blacklist' => 'https://raw.githubusercontent.com/xmugenx/flarum-ext-post-blacklist/master/resources/locale/en.yml',
	'zerosonesfun-announce' => 'https://raw.githubusercontent.com/zerosonesfun/announce/master/resources/locale/en.yml',
	'zhishiq-pusher' => 'https://raw.githubusercontent.com/ZhiShiQ/FlarumPusher/master/locale/en.yaml',
	'zhishiq-queue' => 'https://raw.githubusercontent.com/ZhiShiQ/FlarumQueue/master/locale/en.yaml',
	'zhishiq-redis' => 'https://raw.githubusercontent.com/ZhiShiQ/FlarumRedis/master/locale/en.yaml',
	'ziymed-backtowebsite' => 'https://raw.githubusercontent.com/ziymed/BackToWebsite/master/locale/en.yml',
	/* extensions list end */
];
